[package]
name = "rafttest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raft = "0.4.3"
thiserror = "*"
protobuf = "2.28.0"